# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-08 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
