# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-08 11:22
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20200108_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostForm',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='bio',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
